### ISSUE TITLE
Selinux Lab 2.3.4 issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#89]
- vim is not installed on the machine :-P

- point 2 shows the output of 'cat setup-selinux.yml', the output in the docs differs substantially from what's on the actual VM, in that all vars are missing on the actual lab machine. however the file name setup-selinux.yml.final has all the right content.

- running the ansible with the .final file seem to work except for selinux5 as noted on a previous issue

- no test to check the script worked is present in this lab

**Comment by wrabcak** [comment]
- Vim installed on the system

- setup-selinux.yml removed and setup-selinux.yml.final renamed to setup-selinux.yml

- selinux5 will be fixed in next blueprint

- There is no script, but lab 2.3.5 verifies if the ansible playbook works.

Based on my comments, I think everything is fixed/handled. 

Thanks a lot for review. 
Lukas.

**Comment by lkerner** [comment]
Closed per request of wrabcak.
